# Generated by Django 4.2.2 on 2023-06-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_periodicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
