# Generated by Django 4.2.2 on 2023-06-23 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_habit_streak_habit_streak_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inactivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_inactive_date', models.DateTimeField(blank=True)),
                ('last_inactive_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.habit')),
            ],
        ),
    ]
